# Generated by Django 2.2 on 2019-04-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idautora', models.IntegerField()),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('numerkontaktowy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ksiazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idksiazki', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('nrkontakowy', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Reklamacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idreklamacji', models.IntegerField()),
                ('reklamacja_date', models.DateTimeField(verbose_name='data reklamacji')),
                ('status_reklamacji', models.IntegerField()),
                ('decyzja', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduzytkownika', models.IntegerField()),
                ('typ', models.IntegerField()),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('miasto', models.CharField(max_length=250)),
                ('numertelefonu', models.IntegerField()),
                ('from_date', models.DateTimeField(verbose_name='od kiedy jest w bazie')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idzamowienia', models.IntegerField()),
                ('idrodzaj', models.IntegerField()),
                ('datasprzedazy', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('datadoreczenia', models.CharField(max_length=250)),
                ('order_date', models.DateTimeField(verbose_name='date zamowienia')),
            ],
        ),
    ]
