# Generated by Django 2.2 on 2019-04-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorzy',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uzytkownicy',
            name='email',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
    ]
