# Generated by Django 2.2 on 2019-04-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190411_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazki',
            name='wydawca',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='pub_date',
            field=models.DateTimeField(verbose_name='data wydania'),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='from_date',
            field=models.DateTimeField(verbose_name='godzina dodania'),
        ),
    ]
